In [1]:
# 鸢尾花数据集PCA降维

In [2]:
from sklearn import datasets
import numpy as np

In [3]:
data = datasets.load_iris()["data"]
data.shape

(150, 4)

In [4]:
# 计算4个维度的均值
means = np.mean(data, axis=0)
means

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [5]:
# 样本中心化
data1 = data - means

In [6]:
# 计算x.T 与 T 的矩阵乘积
xTx = np.matmul(data1.T, data1)

In [7]:
xTx

array([[102.16833333,  -6.32266667, 189.873     ,  76.92433333],
       [ -6.32266667,  28.30693333, -49.1188    , -18.12426667],
       [189.873     , -49.1188    , 464.3254    , 193.0458    ],
       [ 76.92433333, -18.12426667, 193.0458    ,  86.56993333]])

In [8]:
feature_values,feature_vectors = np.linalg.eig(xTx)

In [9]:
print("特征值：\n", feature_values)
print("特征向量：\n", feature_vectors)

特征值：
 [630.0080142   36.15794144  11.65321551   3.55142885]
特征向量：
 [[ 0.36138659 -0.65658877 -0.58202985  0.31548719]
 [-0.08452251 -0.73016143  0.59791083 -0.3197231 ]
 [ 0.85667061  0.17337266  0.07623608 -0.47983899]
 [ 0.3582892   0.07548102  0.54583143  0.75365743]]


In [10]:
# 特征值从大到小排序序号
feature_sorts = np.argsort(-feature_values)

In [11]:
# 取特征值最大的2个特征向量
topn = 2
topn_feature_sorts = feature_sorts[:topn]
topn_feature_vectors = feature_vectors[:,topn_feature_sorts]

In [12]:
# 对中心化后的数据降维
data2 = np.matmul(data1, topn_feature_vectors)
data2.shape

(150, 2)

In [13]:
# data <- 原数据
# data1 <- data中心化后
# data2 <- data1降维

In [14]:
# 还原data2
_data1 = np.matmul(data2, topn_feature_vectors.T)
_data = _data1 + means

In [15]:
# 误差
((_data-data)*(_data-data)).sum()/(data*data).sum()

0.0015938968580931022